version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: yarn install
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: yarn install
      - run: yarn deploy
  backup-database:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: yarn install
      - run: yarn backup-database
      ## just for testing
      ## - run: curl https://www.webhook.site/2c37e497-98c1-4474-b28b-80fb576a3222?backup=backup-database-ci
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
  backup-productin:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - backup-database